receivers:
  otlp:
    protocols:
      grpc:
      grpc:
        endpoint: 0.0.0.0:55680
      http:
        endpoint: "0.0.0.0:55690"
        cors_allowed_headers:
          - "*"

exporters:
  otlp:
    endpoint: apm-server:8200
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      exporters: [otlp]